# Generated by Django 3.2.3 on 2021-06-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0004_auto_20210605_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='current_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='current_value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
