# Generated by Django 3.2.3 on 2021-06-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0006_auto_20210605_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
