# Generated by Django 3.2.3 on 2021-06-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0007_position_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='cost_basis',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='profit_loss',
            field=models.FloatField(null=True),
        ),
    ]
