# Generated by Django 3.2.3 on 2021-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0008_auto_20210605_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='cost_basis',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='current_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
