# Generated by Django 3.2.3 on 2021-06-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0009_auto_20210605_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='get_historic',
            field=models.BooleanField(default=False),
        ),
    ]
