# Generated by Django 3.2.3 on 2021-06-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0010_position_get_historic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='get_historic',
        ),
    ]
